project:
  type: website
  output-dir: docs

website:
  title: "personal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - qualifications.qmd
  open-graph:
    locale: es_ES
    site-name: "Joshua Hyatt"


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



