project:
  type: website
  output-dir: docs
  resources:
    - assets/Joshua-Hyatt-Resume.pdf
  site-url: "https://joshuacharleshyatt.github.io/personal"

website:
  title: "Joshua Hyatt"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: qualifications.qmd
        text: Qualifications
  open-graph:
    locale: es_ES
    site-name: "Joshua Hyatt"


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false



